# Generated by Django 5.0 on 2024-01-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorybyclasses', '0003_remove_categorybyclasses_tutor'),
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtutors',
            name='class_category',
            field=models.ManyToManyField(to='categorybyclasses.categorybyclasses'),
        ),
    ]
