# Generated by Django 5.0 on 2024-01-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0002_addtutors_class_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='addtutors',
            name='subject',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
