# Generated by Django 5.0 on 2024-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_alter_addtutors_user_alter_review_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtutors',
            name='number',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
