# Generated by Django 5.0 on 2024-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0005_addtutors_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
