# Generated by Django 5.0 on 2024-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorybyclasses', '0001_initial'),
        ('tution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybyclasses',
            name='tutor',
            field=models.ManyToManyField(to='tution.addtutors'),
        ),
    ]
