# Generated by Django 5.0 on 2024-01-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorybyclasses', '0002_categorybyclasses_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybyclasses',
            name='tutor',
        ),
    ]
