# Generated by Django 5.0 on 2024-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tuitionapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionapplication',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
