# Generated by Django 5.0 on 2024-01-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_tuitionapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuitionApplication',
        ),
    ]
