# Generated by Django 5.0 on 2024-01-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_tuitionapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='is_approved',
            new_name='admin_approval',
        ),
    ]
