# Generated by Django 5.0 on 2024-01-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_is_approved_userinformation_admin_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='admin_approval',
        ),
    ]
